[package]
name = "deepseek_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_deepseek"
path = "test_deepseek.rs"

[dependencies]
rig-core = { path = "./rig-core" }
tokio = { version = "1.45", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0"